import React, { useState } from "react";

const About = () => {
  const [active, setActive] = useState("bio");
  return (
    <>
      <section id="about" className="pt-32 min-h-screen">
        <h1 className="text-sectionfcolor font-bold text-center text-7xl sm:text-8xl md:text-[120px]">
          ABOUT
        </h1>
        <div className="md:flex items-center md:gap-[100px] mt-8 md:mt-14">
          <div>
            <img
              src="/images/aboutImg.png"
              alt="my image generated by AI"
              className="rounded-2xl hidden lg:block"
            />
          </div>
          <div className="text-white p-5 md:p-0">
            <div className="flex gap-3 md:gap-20 mb-4">
              <div
                  onClick={() => setActive("bio")}
                className={`py-1.5 px-3  hover:bg-hoverBg  rounded-sm ${
                  active === "bio" ? "bg-hoverBg" : null
                }`}
              >
                <button
                  className={`${
                    active === "bio"
                      ? "text-primaryText font-bold"
                      : "text-white"
                  }`}
                >
                  Bio
                </button>
              </div>
              <div
                onClick={() => setActive("education")}
                className={`py-1.5 px-3  hover:bg-hoverBg  rounded-sm ${
                  active === "education" ? "bg-hoverBg" : null
                }`}
              >
                <button
                  className={`${
                    active === "education"
                      ? "text-primaryText font-bold"
                      : "text-white"
                  }`}
                >
                  Education
                </button>
              </div>
              <div
                onClick={() => setActive("experience")}
                className={`py-1.5 px-3  hover:bg-hoverBg  rounded-sm ${
                  active === "experience" ? "bg-hoverBg" : null
                }`}
              >
                <button
                  className={`${
                    active === "experience"
                      ? "text-primaryText font-bold"
                      : "text-white"
                  }`}
                >
                  Experience
                </button>
              </div>
            </div>
            <div className="w-full h-0.5 bg-hoverBg my-1.5"></div>
            {active === "bio" && (
              <div>
                <p className="text-sm font-light leading-5 text-gray-400">
                  <span className="block">
                    I’m a developer who loves solving problems and creating
                    things that live on the internet.
                  </span>
                  <span className="block">
                    Coding started as curiosity, grew into a learning journey,
                    and now drives me to
                  </span>
                  <span className="block">
                    build real-world applications with purpose. I enjoy
                    challenges, learning fast, and
                  </span>
                  <span className="block">
                    collaborating to bring meaningful ideas to life through
                    technology.
                  </span>
                </p>
                <div className="block md:flex gap-10 mt-10 text-sm md:text-md">
                  <div className="flex flex-col ">
                    <div className="mb-8">
                      <p>
                        <span className="text-primaryText">Age</span>
                        <span> : . . . 21</span>
                      </p>
                    </div>
                    <div className="mb-8">
                      <p>
                        <span className="text-primaryText">Availability</span>
                        <span> : . . . Open to Opportunities</span>
                      </p>
                    </div>
                    <div className="mb-8">
                      <p>
                        <span className="text-primaryText">Phone</span>
                        <span> : . . . +91 96008-96499</span>
                      </p>
                    </div>
                  </div>
                  <div className="flex flex-col">
                    <div className="mb-8">
                      <p>
                        <span className="text-primaryText">Nationality</span>
                        <span> : . . . INDIA</span>
                      </p>
                    </div>
                    <div className="mb-8">
                      <p>
                        <span className="text-primaryText">Email</span>
                        <span> : . . . jeeva.viswanathan04@gmail.com</span>
                      </p>
                    </div>
                  </div>
                </div>
                <div className="flex gap-5">
                  <div className="py-3.5 px-6 border border-primaryText rounded-md ">
                    <a href="#contact">Contact Me</a>
                  </div>
                  <div className="py-3.5 px-6 bg-primaryText font-bold rounded-md">
                    <a href="">Hire Me</a>
                  </div>
                </div>
              </div>
            )}
            {active === "education" && (
              <div>
                <h3 className="mt-5">
                  <span className="text-primaryText">Degree</span> :
                </h3>
                <p className="text-sm font-light mt-2 ">
                  <span className="block">
                    B.E. Computer Science and Engineering (2022- 2026)
                  </span>
                  <span className="block">
                    Karpaga Vinayaga College of Engineering and Technology
                  </span>
                </p>
                <h3 className="mt-5">
                  <span className="text-primaryText">Summary</span> :
                </h3>
                <p className="max-w-[690px] text-md   leading-6 text-sm font-light mt-2 ">
                  I am currently in my final year, maintaining a 7.5 CGPA. My
                  education inspired my interest in full-stack development,
                  helping me apply theory to real projects and collaborate using
                  tools like Git, React, and Firebase. I consistently explore
                  new technologies and participate in workshops to stay updated
                  with modern development trends.
                </p>
                <div className="flex gap-5 mt-10">
                  <div className="py-3.5 px-6 border border-primaryText rounded-md ">
                    <a href="#contact">Contact Me</a>
                  </div>
                  <div className="py-3.5 px-6 bg-primaryText font-bold rounded-md">
                    <a href="">Hire Me</a>
                  </div>
                </div>
              </div>
            )}
            {active === "experience" && (
              <div>
                <h3 className="mt-5">
                  <span className="text-primaryText">Role</span> :
                </h3>
                <p className="text-sm font-light mt-2 ">
                  <span className="block">
                    React.js Intern — Top Tech developers Pvt Ltd
                  </span>
                  <span className="block">
                    (3 Feb 2025 – 3 mar 2025, Chennai, Tamil Nadu)
                  </span>
                </p>
                <h3 className="mt-5">
                  <span className="text-primaryText">Summary</span> :
                </h3>
                <p className="max-w-[690px] text-md   leading-6 text-sm font-light mt-2 ">
                  I contributed to building dynamic and responsive web
                  interfaces using React.js, JavaScript, and Tailwind CSS.
                  During the internship, I worked closely with other developers
                  in an Agile environment, integrated REST APIs, and managed
                  component state efficiently with React Hooks. I also
                  collaborated using Git and GitHub, participated in code
                  reviews through pull requests, and focused on writing clean
                  and reusable UI components.
                </p>
                <div className="flex gap-5 mt-10">
                  <div className="py-3.5 px-6 border border-primaryText rounded-md ">
                    <a href="#contact">Contact Me</a>
                  </div>
                  <div className="py-3.5 px-6 bg-[#3C54DB] active:bg-[#3B52C3] hover:bg-primaryText font-bold rounded-md">
                    <a href="#contact">Hire Me</a>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </section>
    </>
  );
};

export default About;
